export const SOCAL_COMMON_NAMES: string[] = [
"Black-bellied Whistling-Duck",
"Fulvous Whistling-Duck",
"Emperor Goose",
"Snow Goose",
"Ross's Goose",
"Greater White-fronted Goose",
"Tundra Bean-Goose",
"Brant",
"Cackling Goose",
"Canada Goose",
"Tundra Swan",
"Egyptian Goose",
"Wood Duck",
"Baikal Teal",
"Garganey",
"Blue-winged Teal",
"Cinnamon Teal",
"Northern Shoveler",
"Gadwall",
"Falcated Duck",
"Eurasian Wigeon",
"American Wigeon",
"Mallard",
"Mexican Duck",
"Northern Pintail",
"Green-winged Teal",
"Canvasback",
"Redhead",
"Common Pochard",
"Ring-necked Duck",
"Tufted Duck",
"Greater Scaup",
"Lesser Scaup",
"King Eider",
"Harlequin Duck",
"Surf Scoter",
"White-winged Scoter",
"Black Scoter",
"Long-tailed Duck",
"Bufflehead",
"Common Goldeneye",
"Barrow's Goldeneye",
"Hooded Merganser",
"Common Merganser",
"Red-breasted Merganser",
"Ruddy Duck",
"Helmeted Guineafowl",
"California Quail",
"Gambel's Quail",
"Wild Turkey",
"Sooty Grouse",
"Ring-necked Pheasant",
"Indian Peafowl",
"Chukar",
"Rock Pigeon",
"Band-tailed Pigeon",
"Eurasian Collared-Dove",
"Spotted Dove",
"Inca Dove",
"Common Ground Dove",
"Ruddy Ground Dove",
"White-winged Dove",
"Mourning Dove",
"Groove-billed Ani",
"Greater Roadrunner",
"Yellow-billed Cuckoo",
"Black-billed Cuckoo",
"Lesser Nighthawk",
"Common Nighthawk",
"Common Poorwill",
"Buff-collared Nightjar",
"Eastern Whip-poor-will",
"Mexican Whip-poor-will",
"Black Swift",
"Chimney Swift",
"Vaux's Swift",
"Common Swift",
"White-throated Swift",
"Mexican Violetear",
"Rivoli's Hummingbird",
"Blue-throated Mountain-gem",
"Ruby-throated Hummingbird",
"Black-chinned Hummingbird",
"Anna's Hummingbird",
"Costa's Hummingbird",
"Calliope Hummingbird",
"Rufous Hummingbird",
"Allen's Hummingbird",
"Broad-tailed Hummingbird",
"Broad-billed Hummingbird",
"Xantus's Hummingbird",
"Violet-crowned Hummingbird",
"Ridgway's Rail",
"Virginia Rail",
"Sora",
"Common Gallinule",
"American Coot",
"Purple Gallinule",
"Yellow Rail",
"Black Rail",
"Sandhill Crane",
"Black-necked Stilt",
"American Avocet",
"American Oystercatcher",
"Black Oystercatcher",
"Black-bellied Plover",
"American Golden-Plover",
"Pacific Golden-Plover",
"Eurasian Dotterel",
"Killdeer",
"Common Ringed Plover",
"Semipalmated Plover",
"Piping Plover",
"Siberian Sand-Plover",
"Wilson's Plover",
"Mountain Plover",
"Snowy Plover",
"Upland Sandpiper",
"Hudsonian Whimbrel",
"Eurasian Whimbrel",
"Little Curlew",
"Long-billed Curlew",
"Bar-tailed Godwit",
"Hudsonian Godwit",
"Marbled Godwit",
"Short-billed Dowitcher",
"Long-billed Dowitcher",
"American Woodcock",
"Common Snipe",
"Wilson's Snipe",
"Wilson's Phalarope",
"Red Phalarope",
"Red-necked Phalarope",
"Spotted Sandpiper",
"Solitary Sandpiper",
"Gray-tailed Tattler",
"Wandering Tattler",
"Marsh Sandpiper",
"Wood Sandpiper",
"Lesser Yellowlegs",
"Willet",
"Spotted Redshank",
"Greater Yellowlegs",
"Ruddy Turnstone",
"Black Turnstone",
"Red Knot",
"Surfbird",
"Ruff",
"Sharp-tailed Sandpiper",
"Curlew Sandpiper",
"Stilt Sandpiper",
"Red-necked Stint",
"Buff-breasted Sandpiper",
"Sanderling",
"Dunlin",
"Purple Sandpiper",
"Rock Sandpiper",
"Baird's Sandpiper",
"Little Stint",
"White-rumped Sandpiper",
"Least Sandpiper",
"Pectoral Sandpiper",
"Western Sandpiper",
"Semipalmated Sandpiper",
];