export const EXPANDED_POOL: string[] = [
"Snow Goose",
"Ross's Goose",
"Greater White-fronted Goose",
"Brant",
"Cackling Goose",
"Canada Goose",
"Tundra Swan",
"Egyptian Goose",
"Wood Duck",
"Blue-winged Teal",
"Cinnamon Teal",
"Northern Shoveler",
"Gadwall",
"Eurasian Wigeon",
"American Wigeon",
"Mallard",
"Northern Pintail",
"Green-winged Teal",
"Canvasback",
"Redhead",
"Ring-necked Duck",
"Tufted Duck",
"Greater Scaup",
"Lesser Scaup",
"Harlequin Duck",
"Surf Scoter",
"White-winged Scoter",
"Black Scoter",
"Long-tailed Duck",
"Bufflehead",
"Common Goldeneye",
"Barrow's Goldeneye",
"Hooded Merganser",
"Common Merganser",
"Red-breasted Merganser",
"Ruddy Duck",
"Mountain Quail",
"California Quail",
"Gambel's Quail",
"Wild Turkey",
"Sooty Grouse",
"Ring-necked Pheasant",
"Indian Peafowl",
"Chukar",
"Rock Pigeon",
"Band-tailed Pigeon",
"Eurasian Collared-Dove",
"Spotted Dove",
"Inca Dove",
"Common Ground Dove",
"White-winged Dove",
"Mourning Dove",
"Greater Roadrunner",
"Lesser Nighthawk",
"Common Nighthawk",
"Common Poorwill",
"Black Swift",
"Vaux's Swift",
"White-throated Swift",
"Black-chinned Hummingbird",
"Anna's Hummingbird",
"Costa's Hummingbird",
"Calliope Hummingbird",
"Rufous Hummingbird",
"Allen's Hummingbird",
"Ridgway's Rail",
"Virginia Rail",
"Sora",
"Common Gallinule",
"American Coot",
"Black Rail",
"Sandhill Crane",
"Black-necked Stilt",
"American Avocet",
"Black Oystercatcher",
"Black-bellied Plover",
"Pacific Golden-Plover",
"Killdeer",
"Semipalmated Plover",
"Mountain Plover",
"Snowy Plover",
"Hudsonian Whimbrel",
"Long-billed Curlew",
"Marbled Godwit",
"Short-billed Dowitcher",
"Long-billed Dowitcher",
"Wilson's Snipe",
"Wilson's Phalarope",
"Red Phalarope",
"Red-necked Phalarope",
"Spotted Sandpiper",
"Solitary Sandpiper",
"Wandering Tattler",
"Lesser Yellowlegs",
"Willet",
"Greater Yellowlegs",
"Ruddy Turnstone",
"Black Turnstone",
"Red Knot",
"Surfbird",
"Ruff",
"Stilt Sandpiper",
"Sanderling",
"Dunlin",
"Rock Sandpiper",
"Baird's Sandpiper",
"Least Sandpiper",
"Pectoral Sandpiper",
"Western Sandpiper",
"Semipalmated Sandpiper",
"Long-tailed Jaeger",
"Parasitic Jaeger",
"Pomarine Jaeger",
"South Polar Skua",
"Rhinoceros Auklet",
"Tufted Puffin",
"Cassin's Auklet",
"Marbled Murrelet",
"Pigeon Guillemot",
"Common Murre",
"Ancient Murrelet",
"Scripps's Murrelet",
"Black-legged Kittiwake",
"Sabine's Gull",
"Bonaparte's Gull",
"Laughing Gull",
"Franklin's Gull",
"Heermann's Gull",
"Short-billed Gull",
"Ring-billed Gull",
"Yellow-footed Gull",
"Western Gull",
"American Herring Gull",
"Glaucous Gull",
"Lesser Black-backed Gull",
"California Gull",
"Glaucous-winged Gull",
"Iceland Gull",
"Black Skimmer",
"Least Tern",
"Gull-billed Tern",
"Caspian Tern",
"Black Tern",
"Forster's Tern",
"Arctic Tern",
"Common Tern",
"Elegant Tern",
"Royal Tern",
"Pied-billed Grebe",
"Horned Grebe",
"Red-necked Grebe",
"Eared Grebe",
"Western Grebe",
"Clark's Grebe",
"Red-throated Loon",
"Pacific Loon",
"Common Loon",
"Black-footed Albatross",
"Leach's Storm-Petrel",
"Ashy Storm-Petrel",
"Black Storm-Petrel",
"Northern Fulmar",
"Pink-footed Shearwater",
"Sooty Shearwater",
"Black-vented Shearwater",
"Cocos Booby",
"Brandt's Cormorant",
"Pelagic Cormorant",
"Double-crested Cormorant",
"Neotropic Cormorant",
"White-faced Ibis",
"American Bittern",
"Least Bittern",
"Yellow-crowned Night Heron",
"Black-crowned Night Heron",
"Little Blue Heron",
"Tricolored Heron",
"Reddish Egret",
"Snowy Egret",
"Green Heron",
"Western Cattle-Egret",
"Great Egret",
"Great Blue Heron",
"American White Pelican",
"Brown Pelican",
"California Condor",
"Turkey Vulture",
"Osprey",
"White-tailed Kite",
"Golden Eagle",
"Sharp-shinned Hawk",
"Cooper's Hawk",
"American Goshawk",
"Northern Harrier",
"Bald Eagle",
"Broad-winged Hawk",
"Red-shouldered Hawk",
"Zone-tailed Hawk",
"Swainson's Hawk",
"Red-tailed Hawk",
"Rough-legged Hawk",
"Ferruginous Hawk",
"American Barn Owl",
"Western Screech-Owl",
"Great Horned Owl",
"Northern Pygmy-Owl",
"Burrowing Owl",
"Spotted Owl",
"Long-eared Owl",
"Short-eared Owl",
"Northern Saw-whet Owl",
"Belted Kingfisher",
"Williamson's Sapsucker",
"Yellow-bellied Sapsucker",
"Red-naped Sapsucker",
"Red-breasted Sapsucker",
"Lewis's Woodpecker",
"Red-headed Woodpecker",
"Acorn Woodpecker",
"Gila Woodpecker",
"Black-backed Woodpecker",
"Downy Woodpecker",
"Nuttall's Woodpecker",
"Ladder-backed Woodpecker",
"Hairy Woodpecker",
"White-headed Woodpecker",
"Pileated Woodpecker",
"Northern Flicker",
"American Kestrel",
"Merlin",
"Peregrine Falcon",
"Prairie Falcon",
"Yellow-chevroned Parakeet",
"Red-crowned Amazon",
"Lilac-crowned Amazon",
"Yellow-headed Amazon",
"Nanday Parakeet",
"Mitred Parakeet",
"Red-masked Parakeet",
"Olive-sided Flycatcher",
"Western Wood-Pewee",
"Willow Flycatcher",
"Hammond's Flycatcher",
"Gray Flycatcher",
"Dusky Flycatcher",
"Western Flycatcher",
"Black Phoebe",
"Eastern Phoebe",
"Say's Phoebe",
"Vermilion Flycatcher",
"Ash-throated Flycatcher",
"Brown-crested Flycatcher",
"Tropical Kingbird",
"Cassin's Kingbird",
"Thick-billed Kingbird",
"Western Kingbird",
"Bell's Vireo",
"Hutton's Vireo",
"Cassin's Vireo",
"Plumbeous Vireo",
"Western Warbling Vireo",
"Loggerhead Shrike",
"Pinyon Jay",
"Steller's Jay",
"Island Scrub-Jay",
"California Scrub-Jay",
"Woodhouse's Scrub-Jay",
"Yellow-billed Magpie",
"Clark's Nutcracker",
"American Crow",
"Common Raven",
"Mountain Chickadee",
"Chestnut-backed Chickadee",
"Oak Titmouse",
"Juniper Titmouse",
"Verdin",
"Horned Lark",
"Bank Swallow",
"Tree Swallow",
"Violet-green Swallow",
"Purple Martin",
"Northern Rough-winged Swallow",
"Barn Swallow",
"Cliff Swallow",
"Red-whiskered Bulbul",
"Bushtit",
"Wrentit",
"Swinhoe's White-eye",
"Ruby-crowned Kinglet",
"Golden-crowned Kinglet",
"White-breasted Nuthatch",
"Pygmy Nuthatch",
"Red-breasted Nuthatch",
"Brown Creeper",
"Blue-gray Gnatcatcher",
"Black-tailed Gnatcatcher",
"California Gnatcatcher",
"Rock Wren",
"Canyon Wren",
"Northern House Wren",
"Pacific Wren",
"Marsh Wren",
"Bewick's Wren",
"Cactus Wren",
"American Dipper",
"European Starling",
"Gray Catbird",
"California Thrasher",
"LeConte's Thrasher",
"Crissal Thrasher",
"Sage Thrasher",
"Northern Mockingbird",
"Western Bluebird",
"Mountain Bluebird",
"Townsend's Solitaire",
"Varied Thrush",
"Swainson's Thrush",
"Hermit Thrush",
"American Robin",
"Cedar Waxwing",
"Phainopepla",
"Northern Red Bishop",
"Scaly-breasted Munia",
"Pin-tailed Whydah",
"House Sparrow",
"American Pipit",
"Evening Grosbeak",
"House Finch",
"Purple Finch",
"Cassin's Finch",
"Red Crossbill",
"Pine Siskin",
"Lesser Goldfinch",
"Lawrence's Goldfinch",
"American Goldfinch",
"Lapland Longspur",
"Grasshopper Sparrow",
"Chipping Sparrow",
"Clay-colored Sparrow",
"Black-chinned Sparrow",
"Brewer's Sparrow",
"Black-throated Sparrow",
"Lark Sparrow",
"Lark Bunting",
"Fox Sparrow",
"Dark-eyed Junco",
"White-crowned Sparrow",
"Golden-crowned Sparrow",
"Harris's Sparrow",
"White-throated Sparrow",
"Sagebrush Sparrow",
"Bell's Sparrow",
"Vesper Sparrow",
"Savannah Sparrow",
"Song Sparrow",
"Lincoln's Sparrow",
"Swamp Sparrow",
"Abert's Towhee",
"California Towhee",
"Rufous-crowned Sparrow",
"Green-tailed Towhee",
"Spotted Towhee",
"Yellow-breasted Chat",
"Yellow-headed Blackbird",
"Bobolink",
"Western Meadowlark",
"Orchard Oriole",
"Hooded Oriole",
"Bullock's Oriole",
"Baltimore Oriole",
"Scott's Oriole",
"Red-winged Blackbird",
"Tricolored Blackbird",
"Brown-headed Cowbird",
"Brewer's Blackbird",
"Great-tailed Grackle",
"Ovenbird",
"Northern Waterthrush",
"Black-and-white Warbler",
"Tennessee Warbler",
"Orange-crowned Warbler",
"Lucy's Warbler",
"Nashville Warbler",
"Virginia's Warbler",
"MacGillivray's Warbler",
"Common Yellowthroat",
"American Redstart",
"Northern Parula",
"Magnolia Warbler",
"Blackburnian Warbler",
"Northern Yellow Warbler",
"Chestnut-sided Warbler",
"Blackpoll Warbler",
"Black-throated Blue Warbler",
"Palm Warbler",
"Yellow-rumped Warbler",
"Black-throated Gray Warbler",
"Townsend's Warbler",
"Hermit Warbler",
"Wilson's Warbler",
"Painted Redstart",
"Summer Tanager",
"Western Tanager",
"Rose-breasted Grosbeak",
"Black-headed Grosbeak",
"Blue Grosbeak",
"Lazuli Bunting",
"Indigo Bunting",
];