export const FLYCATCHER_POOL: string[] = [
"Olive-sided Flycatcher",
"Greater Pewee",
"Western Wood-Pewee",
"Eastern Wood-Pewee",
"Yellow-bellied Flycatcher",
"Alder Flycatcher",
"Willow Flycatcher",
"Least Flycatcher",
"Hammond's Flycatcher",
"Gray Flycatcher",
"Dusky Flycatcher",
"Western Flycatcher",
"Buff-breasted Flycatcher",
"Black Phoebe",
"Eastern Phoebe",
"Say's Phoebe",
"Vermilion Flycatcher",
"Dusky-capped Flycatcher",
"Ash-throated Flycatcher",
"Nutting's Flycatcher",
"Great Crested Flycatcher",
"Brown-crested Flycatcher",
"Sulphur-bellied Flycatcher",
"Tropical Kingbird",
"Couch's Kingbird",
"Cassin's Kingbird",
"Thick-billed Kingbird",
"Western Kingbird",
"Eastern Kingbird",
"Scissor-tailed Flycatcher",
"Fork-tailed Flycatcher",
];