export const GULL_POOL: string[] = [
"Swallow-tailed Gull",
"Little Gull",
"Ross's Gull",
"Black-legged Kittiwake",
"Red-legged Kittiwake",
"Ivory Gull",
"Sabine's Gull",
"Bonaparte's Gull",
"Black-headed Gull",
"Laughing Gull",
"Franklin's Gull",
"Belcher's Gull",
"Black-tailed Gull",
"Heermann's Gull",
"Short-billed Gull",
"Ring-billed Gull",
"Yellow-footed Gull",
"Western Gull",
"Kelp Gull",
"American Herring Gull",
"Vega Gull",
"Great Black-backed Gull",
"Glaucous Gull",
"Lesser Black-backed Gull",
"California Gull",
"Glaucous-winged Gull",
"Slaty-backed Gull",
"Iceland Gull",
"Black Skimmer",
"Sooty Tern",
"Bridled Tern",
"Least Tern",
"Gull-billed Tern",
"Caspian Tern",
"Black Tern",
"White-winged Tern",
"Forster's Tern",
"Arctic Tern",
"Common Tern",
"Sandwich Tern",
"Elegant Tern",
"Royal Tern",
];