export const SHOREBIRD_POOL: string[] = [
"Ridgway's Rail",
"Virginia Rail",
"Sora",
"Common Gallinule",
"American Coot",
"Purple Gallinule",
"Yellow Rail",
"Black Rail",
"Black-necked Stilt",
"American Avocet",
"American Oystercatcher",
"Black Oystercatcher",
"Black-bellied Plover",
"American Golden-Plover",
"Pacific Golden-Plover",
"Eurasian Dotterel",
"Killdeer",
"Common Ringed Plover",
"Semipalmated Plover",
"Piping Plover",
"Siberian Sand-Plover",
"Wilson's Plover",
"Mountain Plover",
"Snowy Plover",
"Upland Sandpiper",
"Hudsonian Whimbrel",
"Eurasian Whimbrel",
"Little Curlew",
"Long-billed Curlew",
"Bar-tailed Godwit",
"Hudsonian Godwit",
"Marbled Godwit",
"Short-billed Dowitcher",
"Long-billed Dowitcher",
"American Woodcock",
"Common Snipe",
"Wilson's Snipe",
"Wilson's Phalarope",
"Red Phalarope",
"Red-necked Phalarope",
"Spotted Sandpiper",
"Solitary Sandpiper",
"Gray-tailed Tattler",
"Wandering Tattler",
"Marsh Sandpiper",
"Wood Sandpiper",
"Lesser Yellowlegs",
"Willet",
"Spotted Redshank",
"Greater Yellowlegs",
"Ruddy Turnstone",
"Black Turnstone",
"Red Knot",
"Surfbird",
"Ruff",
"Sharp-tailed Sandpiper",
"Curlew Sandpiper",
"Stilt Sandpiper",
"Red-necked Stint",
"Buff-breasted Sandpiper",
"Sanderling",
"Dunlin",
"Purple Sandpiper",
"Rock Sandpiper",
"Baird's Sandpiper",
"Little Stint",
"White-rumped Sandpiper",
"Least Sandpiper",
"Pectoral Sandpiper",
"Western Sandpiper",
"Semipalmated Sandpiper",
];