export const SPARROW_POOL: string[] = [
"Grasshopper Sparrow",
"Chipping Sparrow",
"Clay-colored Sparrow",
"Black-chinned Sparrow",
"Field Sparrow",
"Brewer's Sparrow",
"Black-throated Sparrow",
"Lark Sparrow",
"Lark Bunting",
"American Tree Sparrow",
"Fox Sparrow",
"Dark-eyed Junco",
"White-crowned Sparrow",
"Golden-crowned Sparrow",
"Harris's Sparrow",
"White-throated Sparrow",
"Sagebrush Sparrow",
"Bell's Sparrow",
"Vesper Sparrow",
"LeConte's Sparrow",
"Nelson's Sparrow",
"Savannah Sparrow",
"Baird's Sparrow",
"Song Sparrow",
"Lincoln's Sparrow",
"Swamp Sparrow",
"Abert's Towhee",
"California Towhee",
"Rufous-crowned Sparrow",
"Green-tailed Towhee",
"Spotted Towhee",
];