export const STANDARD_POOL: string[] = [
"Snow Goose",
"Ross's Goose",
"Greater White-fronted Goose",
"Brant",
"Cackling Goose",
"Canada Goose",
"Tundra Swan",
"Egyptian Goose",
"Wood Duck",
"Blue-winged Teal",
"Cinnamon Teal",
"Northern Shoveler",
"Gadwall",
"American Wigeon",
"Mallard",
"Northern Pintail",
"Green-winged Teal",
"Canvasback",
"Redhead",
"Ring-necked Duck",
"Greater Scaup",
"Lesser Scaup",
"Surf Scoter",
"Bufflehead",
"Common Goldeneye",
"Hooded Merganser",
"Common Merganser",
"Red-breasted Merganser",
"Ruddy Duck",
"Mountain Quail",
"California Quail",
"Gambel's Quail",
"Wild Turkey",
"Ring-necked Pheasant",
"Indian Peafowl",
"Rock Pigeon",
"Band-tailed Pigeon",
"Eurasian Collared-Dove",
"White-winged Dove",
"Mourning Dove",
"Greater Roadrunner",
"Vaux's Swift",
"White-throated Swift",
"Black-chinned Hummingbird",
"Anna's Hummingbird",
"Costa's Hummingbird",
"Allen's Hummingbird",
"Virginia Rail",
"Sora",
"Common Gallinule",
"American Coot",
"Sandhill Crane",
"Black-necked Stilt",
"American Avocet",
"Black Oystercatcher",
"Black-bellied Plover",
"Killdeer",
"Semipalmated Plover",
"Snowy Plover",
"Hudsonian Whimbrel",
"Long-billed Curlew",
"Marbled Godwit",
"Long-billed Dowitcher",
"Wilson's Snipe",
"Wilson's Phalarope",
"Red-necked Phalarope",
"Spotted Sandpiper",
"Willet",
"Ruddy Turnstone",
"Black Turnstone",
"Surfbird",
"Sanderling",
"Dunlin",
"Least Sandpiper",
"Western Sandpiper",
"Pigeon Guillemot",
"Common Murre",
"Bonaparte's Gull",
"Heermann's Gull",
"Short-billed Gull",
"Ring-billed Gull",
"Western Gull",
"American Herring Gull",
"California Gull",
"Glaucous-winged Gull",
"Iceland Gull",
"Black Skimmer",
"Least Tern",
"Caspian Tern",
"Forster's Tern",
"Elegant Tern",
"Royal Tern",
"Pied-billed Grebe",
"Horned Grebe",
"Eared Grebe",
"Western Grebe",
"Clark's Grebe",
"Red-throated Loon",
"Pacific Loon",
"Common Loon",
"Sooty Shearwater",
"Brandt's Cormorant",
"Pelagic Cormorant",
"Double-crested Cormorant",
"Neotropic Cormorant",
"White-faced Ibis",
"American Bittern",
"Least Bittern",
"Yellow-crowned Night Heron",
"Black-crowned Night Heron",
"Reddish Egret",
"Snowy Egret",
"Green Heron",
"Western Cattle-Egret",
"Great Egret",
"Great Blue Heron",
"American White Pelican",
"Brown Pelican",
"Turkey Vulture",
"Osprey",
"White-tailed Kite",
"Golden Eagle",
"Sharp-shinned Hawk",
"Cooper's Hawk",
"Northern Harrier",
"Bald Eagle",
"Red-shouldered Hawk",
"Swainson's Hawk",
"Red-tailed Hawk",
"Ferruginous Hawk",
"American Barn Owl",
"Western Screech-Owl",
"Great Horned Owl",
"Burrowing Owl",
"Belted Kingfisher",
"Red-breasted Sapsucker",
"Lewis's Woodpecker",
"Red-headed Woodpecker",
"Acorn Woodpecker",
"Downy Woodpecker",
"Nuttall's Woodpecker",
"Ladder-backed Woodpecker",
"Hairy Woodpecker",
"White-headed Woodpecker",
"Pileated Woodpecker",
"Northern Flicker",
"American Kestrel",
"Merlin",
"Peregrine Falcon",
"Prairie Falcon",
"Yellow-chevroned Parakeet",
"Red-crowned Amazon",
"Lilac-crowned Amazon",
"Nanday Parakeet",
"Red-masked Parakeet",
"Olive-sided Flycatcher",
"Western Wood-Pewee",
"Western Flycatcher",
"Black Phoebe",
"Eastern Phoebe",
"Say's Phoebe",
"Vermilion Flycatcher",
"Ash-throated Flycatcher",
"Cassin's Kingbird",
"Western Kingbird",
"Bell's Vireo",
"Hutton's Vireo",
"Cassin's Vireo",
"Western Warbling Vireo",
"Loggerhead Shrike",
"Steller's Jay",
"California Scrub-Jay",
"Yellow-billed Magpie",
"Clark's Nutcracker",
"American Crow",
"Common Raven",
"Mountain Chickadee",
"Chestnut-backed Chickadee",
"Oak Titmouse",
"Verdin",
"Horned Lark",
"Tree Swallow",
"Violet-green Swallow",
"Northern Rough-winged Swallow",
"Barn Swallow",
"Cliff Swallow",
"Red-whiskered Bulbul",
"Bushtit",
"Wrentit",
"Swinhoe's White-eye",
"Ruby-crowned Kinglet",
"Golden-crowned Kinglet",
"White-breasted Nuthatch",
"Pygmy Nuthatch",
"Red-breasted Nuthatch",
"Brown Creeper",
"Blue-gray Gnatcatcher",
"California Gnatcatcher",
"Rock Wren",
"Canyon Wren",
"Northern House Wren",
"Marsh Wren",
"Bewick's Wren",
"Cactus Wren",
"European Starling",
"California Thrasher",
"Northern Mockingbird",
"Western Bluebird",
"Mountain Bluebird",
"Townsend's Solitaire",
"Varied Thrush",
"Swainson's Thrush",
"Hermit Thrush",
"American Robin",
"Cedar Waxwing",
"Phainopepla",
"Scaly-breasted Munia",
"Pin-tailed Whydah",
"House Sparrow",
"American Pipit",
"Evening Grosbeak",
"House Finch",
"Purple Finch",
"Cassin's Finch",
"Red Crossbill",
"Pine Siskin",
"Lesser Goldfinch",
"Lawrence's Goldfinch",
"American Goldfinch",
"Chipping Sparrow",
"Brewer's Sparrow",
"Black-throated Sparrow",
"Lark Sparrow",
"Fox Sparrow",
"Dark-eyed Junco",
"White-crowned Sparrow",
"Golden-crowned Sparrow",
"White-throated Sparrow",
"Savannah Sparrow",
"Song Sparrow",
"Lincoln's Sparrow",
"California Towhee",
"Rufous-crowned Sparrow",
"Green-tailed Towhee",
"Spotted Towhee",
"Yellow-breasted Chat",
"Yellow-headed Blackbird",
"Western Meadowlark",
"Hooded Oriole",
"Bullock's Oriole",
"Red-winged Blackbird",
"Tricolored Blackbird",
"Brown-headed Cowbird",
"Brewer's Blackbird",
"Great-tailed Grackle",
"Orange-crowned Warbler",
"Nashville Warbler",
"Virginia's Warbler",
"MacGillivray's Warbler",
"Common Yellowthroat",
"Northern Yellow Warbler",
"Yellow-rumped Warbler",
"Black-throated Gray Warbler",
"Townsend's Warbler",
"Hermit Warbler",
"Wilson's Warbler",
"Western Tanager",
"Black-headed Grosbeak",
"Blue Grosbeak",
"Lazuli Bunting",
];