export const WARBLER_POOL: string[] = [
"Ovenbird",
"Worm-eating Warbler",
"Louisiana Waterthrush",
"Northern Waterthrush",
"Golden-winged Warbler",
"Blue-winged Warbler",
"Black-and-white Warbler",
"Prothonotary Warbler",
"Tennessee Warbler",
"Orange-crowned Warbler",
"Lucy's Warbler",
"Nashville Warbler",
"Virginia's Warbler",
"Connecticut Warbler",
"MacGillivray's Warbler",
"Mourning Warbler",
"Kentucky Warbler",
"Common Yellowthroat",
"Hooded Warbler",
"American Redstart",
"Cape May Warbler",
"Cerulean Warbler",
"Northern Parula",
"Tropical Parula",
"Magnolia Warbler",
"Bay-breasted Warbler",
"Blackburnian Warbler",
"Northern Yellow Warbler",
"Mangrove Yellow Warbler",
"Chestnut-sided Warbler",
"Blackpoll Warbler",
"Black-throated Blue Warbler",
"Palm Warbler",
"Pine Warbler",
"Yellow-rumped Warbler",
"Yellow-throated Warbler",
"Prairie Warbler",
"Grace's Warbler",
"Black-throated Gray Warbler",
"Townsend's Warbler",
"Hermit Warbler",
"Black-throated Green Warbler",
"Canada Warbler",
"Wilson's Warbler",
"Red-faced Warbler",
"Painted Redstart",
];