export const WATERFOWL_POOL: string[] = [
"Emperor Goose",
"Snow Goose",
"Ross's Goose",
"Greater White-fronted Goose",
"Tundra Bean-Goose",
"Brant",
"Cackling Goose",
"Canada Goose",
"Tundra Swan",
"Egyptian Goose",
"Black-bellied Whistling-Duck",
"Fulvous Whistling-Duck",
"Baikal Teal",
"Garganey",
"Blue-winged Teal",
"Cinnamon Teal",
"Northern Shoveler",
"Gadwall",
"Eurasian Wigeon",
"American Wigeon",
"Mallard",
"Mexican Duck",
"Northern Pintail",
"Green-winged Teal",
"Canvasback",
"Redhead",
"Ring-necked Duck",
"Tufted Duck",
"Greater Scaup",
"Lesser Scaup",
"King Eider",
"Harlequin Duck",
"Surf Scoter",
"White-winged Scoter",
"Black Scoter",
"Long-tailed Duck",
"Bufflehead",
"Common Goldeneye",
"Barrow's Goldeneye",
"Hooded Merganser",
"Common Merganser",
"Red-breasted Merganser",
"Ruddy Duck",
];